In [4]:
import pandas as pd
import seaborn as sns

In [5]:
iris = sns.load_dataset('iris')

In [6]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# Amostragem aleatoria simples

In [7]:
df_amostra_simples = iris.sample(n = 10)

In [8]:
df_amostra_simples.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 29 to 133
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  10 non-null     float64
 1   sepal_width   10 non-null     float64
 2   petal_length  10 non-null     float64
 3   petal_width   10 non-null     float64
 4   species       10 non-null     object
dtypes: float64(4), object(1)
memory usage: 480.0+ bytes

In [9]:
df_amostra_simples['species'].value_counts()

species
setosa        7
versicolor    2
virginica     1
Name: count, dtype: int64

Especificando amostra através de percentual

In [13]:
df_amostra_simples = iris.sample(frac=0.10)

In [14]:
df_amostra_simples.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 89 to 125
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  15 non-null     float64
 1   sepal_width   15 non-null     float64
 2   petal_length  15 non-null     float64
 3   petal_width   15 non-null     float64
 4   species       15 non-null     object
dtypes: float64(4), object(1)
memory usage: 720.0+ bytes

In [15]:
df_amostra_simples['species'].value_counts()

species
virginica     7
versicolor    5
setosa        3
Name: count, dtype: int64

# Amostragem sistematica

In [12]:
import numpy as np

In [16]:
semente = np.random.choice(10, 1)

In [17]:
semente

array([5])

In [18]:
# Gerando indice a partir da semente
indices = np.arange(0, 100, semente)
indices

/tmp/ipython-input-181886135.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  indices = np.arange(0, 100, semente)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [19]:
# gerando amostra a apartir do indice
amostra = iris.loc[indices, :]
amostra

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
5            5.4          3.9           1.7          0.4      setosa
10           5.4          3.7           1.5          0.2      setosa
15           5.7          4.4           1.5          0.4      setosa
20           5.4          3.4           1.7          0.2      setosa
25           5.0          3.0           1.6          0.2      setosa
30           4.8          3.1           1.6          0.2      setosa
35           5.0          3.2           1.2          0.2      setosa
40           5.0          3.5           1.3          0.3      setosa
45           4.8          3.0           1.4          0.3      setosa
50           7.0          3.2           4.7          1.4  versicolor
55           5.7          2.8           4.5          1.3  versicolor
60           5.0          2.0           3.5          1.0  versicolor
65           6.7          3.1           4.4          1.4  versicolor
70           5.9          3.2           4.8          1.8  versicolor
75           6.6          3.0           4.4          1.4  versicolor
80           5.5          2.4           3.8          1.1  versicolor
85           6.0          3.4           4.5          1.6  versicolor
90           5.5          2.6           4.4          1.2  versicolor
95           5.7          3.0           4.2          1.2  versicolor

In [20]:
# Verificando a separação da amostra
amostra['species'].value_counts()

species
setosa        10
versicolor    10
Name: count, dtype: int64

# Amostragem Estratificada

In [21]:
from sklearn.model_selection import StratifiedShuffleSplit

In [22]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [23]:
split = StratifiedShuffleSplit(test_size = 0.2)

# A função split.split irá colocar os 80% no X e os 20% no y
for X, y in split.split(iris, iris['species']):
    df_X = iris.iloc[X]
    df_y = iris.iloc[y]

In [24]:
# Para visualizar a amostra basta utilizarmos o df_y
df_y['species'].value_counts()

species
versicolor    10
setosa        10
virginica     10
Name: count, dtype: int64

In [25]:
df_y

     sepal_length  sepal_width  petal_length  petal_width     species
70            5.9          3.2           4.8          1.8  versicolor
9             4.9          3.1           1.5          0.1      setosa
29            4.7          3.2           1.6          0.2      setosa
124           6.7          3.3           5.7          2.1   virginica
27            5.2          3.5           1.5          0.2      setosa
72            6.3          2.5           4.9          1.5  versicolor
3             4.6          3.1           1.5          0.2      setosa
41            4.5          2.3           1.3          0.3      setosa
39            5.1          3.4           1.5          0.2      setosa
104           6.5          3.0           5.8          2.2   virginica
69            5.6          2.5           3.9          1.1  versicolor
16            5.4          3.9           1.3          0.4      setosa
5             5.4          3.9           1.7          0.4      setosa
85            6.0          3.4           4.5          1.6  versicolor
98            5.1          2.5           3.0          1.1  versicolor
103           6.3          2.9           5.6          1.8   virginica
121           5.6          2.8           4.9          2.0   virginica
53            5.5          2.3           4.0          1.3  versicolor
148           6.2          3.4           5.4          2.3   virginica
71            6.1          2.8           4.0          1.3  versicolor
147           6.5          3.0           5.2          2.0   virginica
94            5.6          2.7           4.2          1.3  versicolor
82            5.8          2.7           3.9          1.2  versicolor
102           7.1          3.0           5.9          2.1   virginica
138           6.0          3.0           4.8          1.8   virginica
141           6.9          3.1           5.1          2.3   virginica
2             4.7          3.2           1.3          0.2      setosa
62            6.0          2.2           4.0          1.0  versicolor
23            5.1          3.3           1.7          0.5      setosa
112           6.8          3.0           5.5          2.1   virginica